#!/bin/bash

# ==================================================================
# ISRO LUNAR HABITAT MAINTENANCE ROBOT - COMPLETE SYSTEM LAUNCHER
# ==================================================================

echo "╔══════════════════════════════════════════════════════════════════════╗"
echo "║  🌙 ISRO LUNAR HABITAT MAINTENANCE ROBOT - AUTONOMOUS SYSTEM  🤖    ║"
echo "║              Enhanced Navigation & Object Detection                  ║"
echo "╚══════════════════════════════════════════════════════════════════════╝"
echo ""
echo "This system includes:"
echo "  ✅ Intelligent autonomous navigation with obstacle avoidance"
echo "  ✅ 360° Lidar-based object detection (ROCK/BOULDER/STRUCTURE)"
echo "  ✅ Environmental monitoring (O₂, Temperature, Pressure)"
echo "  ✅ Path tracking and visualization"
echo "  ✅ HQ Control Panel with object database"
echo "  ✅ Real-time telemetry transmission"
echo ""
echo "Follow these steps to launch the complete system:"
echo "══════════════════════════════════════════════════════════════════════"
echo ""

# Source ROS
source /opt/ros/humble/setup.bash
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/ros2_ws/install/setup.bash"

echo "📋 TERMINAL COMMANDS:"
echo "════════════════════════════════════════════════════════════════════=="
echo ""
echo "Open 9 separate terminals and run these commands:"
echo ""

echo "┌─────────────────────────────────────────────────────────────────────┐"
echo "│ TERMINAL 1: Gazebo Simulation                                       │"
echo "└─────────────────────────────────────────────────────────────────────┘"
echo "cd $SCRIPT_DIR"
echo "source /opt/ros/humble/setup.bash"
echo "export IGN_GAZEBO_RESOURCE_PATH=\$IGN_GAZEBO_RESOURCE_PATH:\$(pwd)"
echo "export GZ_SIM_RESOURCE_PATH=\$GZ_SIM_RESOURCE_PATH:\$(pwd)"
echo "ign gazebo -r MyModel.world"
echo "# ✅ Auto-starts in RUN mode"
echo ""

echo "┌─────────────────────────────────────────────────────────────────────┐"
echo "│ TERMINAL 2: ROS-Gazebo Bridge                                       │"
echo "└─────────────────────────────────────────────────────────────────────┘"
echo "source /opt/ros/humble/setup.bash"
echo "ros2 run ros_gz_bridge parameter_bridge \\" 
echo "    /lidar@sensor_msgs/msg/LaserScan[ignition.msgs.LaserScan \\" 
echo "    /odom@nav_msgs/msg/Odometry[ignition.msgs.Odometry \\" 
echo "    /cmd_vel@geometry_msgs/msg/Twist]ignition.msgs.Twist"
echo ""

echo "┌─────────────────────────────────────────────────────────────────────┐"
echo "│ TERMINAL 3: Enhanced Object Detector                                │"
echo "└─────────────────────────────────────────────────────────────────────┘"
echo "source /opt/ros/humble/setup.bash"
echo "source $SCRIPT_DIR/ros2_ws/install/setup.bash"
echo "ros2 run mars_rover_navigation enhanced_object_detector"
echo ""

echo "┌─────────────────────────────────────────────────────────────────────┐"
echo "│ TERMINAL 4: Environmental Monitoring                                │"
echo "└─────────────────────────────────────────────────────────────────────┘"
echo "source /opt/ros/humble/setup.bash"
echo "source $SCRIPT_DIR/ros2_ws/install/setup.bash"
echo "ros2 run mars_rover_navigation environmental_monitor"
echo ""

echo "┌─────────────────────────────────────────────────────────────────────┐"
echo "│ TERMINAL 5: Path Tracker                                            │"
echo "└─────────────────────────────────────────────────────────────────────┘"
echo "source /opt/ros/humble/setup.bash"
echo "source $SCRIPT_DIR/ros2_ws/install/setup.bash"
echo "ros2 run mars_rover_navigation path_tracker"
echo ""

echo "┌─────────────────────────────────────────────────────────────────────┐"
echo "│ TERMINAL 6: TF Publishers                                           │"
echo "└─────────────────────────────────────────────────────────────────────┘"
echo "source /opt/ros/humble/setup.bash"
echo "ros2 run tf2_ros static_transform_publisher 0 0 0 0 0 0 map odom &"
echo "ros2 run tf2_ros static_transform_publisher 0 0 0 0 0 0 odom base_link"
echo ""

echo "┌─────────────────────────────────────────────────────────────────────┐"
echo "│ TERMINAL 7: AUTONOMOUS NAVIGATION ⭐                                │"
echo "└─────────────────────────────────────────────────────────────────────┘"
echo "source /opt/ros/humble/setup.bash"
echo "source $SCRIPT_DIR/ros2_ws/install/setup.bash"
echo "ros2 run mars_rover_navigation autonomous_patrol"
echo "# 🤖 Rover will move autonomously with obstacle avoidance!"
echo ""

echo "┌─────────────────────────────────────────────────────────────────────┐"
echo "│ TERMINAL 8: HQ CONTROL PANEL 🖥️                                     │"
echo "└─────────────────────────────────────────────────────────────────────┘"
echo "source /opt/ros/humble/setup.bash"
echo "source $SCRIPT_DIR/ros2_ws/install/setup.bash"
echo "ros2 run mars_rover_navigation hq_control_panel"
echo "# 📊 Displays all detected objects, path data, telemetry"
echo ""

echo "┌─────────────────────────────────────────────────────────────────────┐"
echo "│ TERMINAL 9: RViz Visualization (Optional)                           │"
echo "└─────────────────────────────────────────────────────────────────────┘"
echo "source /opt/ros/humble/setup.bash"
echo "source $SCRIPT_DIR/ros2_ws/install/setup.bash"
echo "rviz2 -d $SCRIPT_DIR/ros2_ws/src/mars_rover_navigation/config/lunar_habitat_visualization.rviz"
echo "# 🗺️  Shows path (red line), obstacles, robot model"
echo ""

echo "══════════════════════════════════════════════════════════════════════"
echo "✅ SYSTEM FEATURES:"
echo "══════════════════════════════════════════════════════════════════════"
echo "🤖 AUTONOMOUS NAVIGATION:"
echo "   - Intelligent pathfinding with obstacle avoidance"
echo "   - Turn left/right based on clearance analysis"
echo "   - Automatic reversing when boxed in"
echo "   - Exploration mode for area coverage"
echo ""
echo "📦 OBJECT DETECTION:"
echo "   - Lidar-based 360° scanning"
echo "   - Classifies objects: ROCK, BOULDER, STRUCTURE"
echo "   - Sends object names/types to HQ panel"
echo "   - Real-time distance and angle measurements"
echo ""
echo "📊 HQ CONTROL PANEL:"
echo "   - Live object database table"
echo "   - Icons for each object type (🪨🗿🏗️)"
echo "   - Total distance traveled"
echo "   - Path points recorded"
echo "   - Environmental status"
echo "   - Mission time tracking"
echo ""
echo "🗺️  PATH VISUALIZATION:"
echo "   - Complete path shown as red line in RViz"
echo "   - Detected objects marked as colored spheres"
echo "   - Robot model with lidar visualization"
echo ""
echo "══════════════════════════════════════════════════════════════════════"
echo "📝 MONITORING COMMANDS (run in any terminal):"
echo "══════════════════════════════════════════════════════════════════════"
echo ""
echo "# View detected objects:"
echo "ros2 topic echo /object_information"
echo ""
echo "# View navigation status:"
echo "ros2 topic echo /patrol_status"
echo ""
echo "# View environmental data:"
echo "ros2 topic echo /habitat/environmental_status"
echo ""
echo "# View all topics:"
echo "ros2 topic list"
echo ""
echo "══════════════════════════════════════════════════════════════════════"
echo "🎮 MANUAL CONTROL (override autonomous mode):"
echo "══════════════════════════════════════════════════════════════════════"
echo ""
echo "# Move forward:"
echo "ros2 topic pub /cmd_vel geometry_msgs/msg/Twist \"{linear: {x: 0.5}, angular: {z: 0.0}}\" -r 10"
echo ""
echo "# Turn in place:"
echo "ros2 topic pub /cmd_vel geometry_msgs/msg/Twist \"{linear: {x: 0.0}, angular: {z: 0.5}}\" -r 10"
echo ""
echo "# Stop:"
echo "ros2 topic pub /cmd_vel geometry_msgs/msg/Twist \"{linear: {x: 0.0}, angular: {z: 0.0}}\" -r 10"
echo ""
echo "══════════════════════════════════════════════════════════════════════"
echo "🛑 TO STOP ALL PROCESSES:"
echo "══════════════════════════════════════════════════════════════════════"
echo "pkill -9 ign; pkill -9 ros2"
echo ""
echo "══════════════════════════════════════════════════════════════════════"
echo "📚 Documentation: See ISRO_SOLUTION.md for complete details"
echo "══════════════════════════════════════════════════════════════════════"
echo ""
echo "Press Enter to exit..."
read
